# spring이 하는일이라 dotenv-java를 implement해도
# .env에 환경변수 설정하는것으론 DB_ 를 해결하지 못함
# 인데.. main() 부에서 직접 dotnev 관련설정을 해서 해결
spring:
  datasource:
    url: jdbc:oracle:thin:@tcps://${DB_HOST}:${DB_PORT}/${DB_SERVICE_NAME}?ssl_server_dn_match=no
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  hikari:
    maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update   # ★ 테이블 자동 생성/업데이트
    show-sql: true        # ★ SQL 쿼리 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect # ★ 오라클용 방언 설정

# Spring Boot는 기본적으로는 INFO로 처리한다고 한다
logging:
  level:
    root: INFO



# 챗지피티 관련
openai:
  api-key: ${OPENAI_API_KEY}

# 비밀 키 (로그인 관련)
jwt:
  secret: ${jwt.secret}

