# spring이 하는일이라 dotenv-java를 implement해도
# .env에 환경변수 설정하는것으론 DB_ 를 해결하지 못함
# 인데.. main() 부에서 직접 dotnev 관련설정을 해서 해결
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/nun  # DB URL은 공개되어도 괜찮음
    username: ${DB_USERNAME}  # 환경 변수로 DB 사용자명 설정
    password: ${DB_PASSWORD}  # 환경 변수로 DB 비밀번호 설정
    driver-class-name: oracle.jdbc.OracleDriver
  hikari:
    maximum-pool-size: 10

logging:
  level:
    org.springframework.web: DEBUG  # 웹 요청 관련 디버그 정보
    org.hibernate: DEBUG             # Hibernate 관련 디버그 정보


# 챗지피티 관련
openai:
  api-key: ${OPENAI_API_KEY}


